version: '3.1'

services:

  db:
    container_name: user-mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/scripts:/docker-entrypoint-initdb.d

  user-app:
    container_name: user-app
    image: daveharms/userservice
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=user-mysql-db
      - DATABASE_USER=useradmin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=userdb
      - DATABASE_PORT=3306