DROP DATABASE IF EXISTS userdb;
DROP USER IF EXISTS `useradmin`@`%`;
DROP USER IF EXISTS `useruser`@`%`;
CREATE DATABASE IF NOT EXISTS userdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `useradmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `userdb`.* TO `useradmin`@`%`;
CREATE USER IF NOT EXISTS `useruser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `userdb`.* TO `useruser`@`%`;
FLUSH PRIVILEGES;